version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo-server
    ports:
      - 27017:27017
    volumes:
      - mongo-server-data:/data/db
      - mongo-server-config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:Test1234

  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql-server
    ports:
      - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234
      - MSSQL_PID=Express

  rabbit:
    image: rabbitmq:management
    container_name: rabbit-server
    hostname: rabbit-server
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit-server-data:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-server-data:/data

  neo4j:
    image: neo4j
    container_name: neo4j-server
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j-server-data:/data
      - neo4j-server-logs:/logs


volumes:
  sql-server-data:
  redis-server-data:
  rabbit-server-data:
  mongo-server-data:
  mongo-server-config:
  neo4j-server-data:
  neo4j-server-logs:
