version: '3'

services:

  mongo:
    image: mongo
    container_name: mongo-server
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:Test1234

  sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql-server
    ports:
      - 1433:1433
    volumes:
      - sql-server-data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test1234
      - MSSQL_PID=Express

  rabbit:
    image: rabbitmq:management
    container_name: rabbit-server
    hostname: rabbit-server
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis
    container_name: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis-server-data:/data


volumes:
  sql-server-data:
  redis-server-data:
